Chore: 빌드 테스트

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,4 +1,4 @@
-name: Deploy Poppin Dev.
+name: Deploy Poppin Dev
 
 on:
   push:
@@ -105,6 +105,21 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
           AWS_S3_DEV_BUCKET_NAME: ${{ secrets.AWS_S3_DEV_BUCKET_NAME }}
+
+      - name: Check if ZIP file exists in S3
+        run: |
+          echo "Checking if ZIP file exists in S3..."
+          aws s3 ls s3://$AWS_S3_DEV_BUCKET_NAME/deploy-${{ env.VERSION }}.zip || { echo "ZIP file not found! Exiting..."; exit 1; }
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          AWS_S3_DEV_BUCKET_NAME: ${{ secrets.AWS_S3_DEV_BUCKET_NAME }}
+
+      - name: Wait for Elastic Beanstalk to Process Application Version
+        run: |
+          echo "Waiting for Elastic Beanstalk to process the new application version..."
+          sleep 30
 
       - name: Deploy to Elastic Beanstalk
         run: |
